services:
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile.bot
    container_name: monitoring_bot
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    volumes:
      - sqlite_data:/app/data
    restart: always
    networks:
      - monitoring-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  web:
    build:
      context: .
      dockerfile: web/Dockerfile.web
    container_name: monitoring_web_app
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
    restart: always
    networks:
      - monitoring-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
networks:
  monitoring-network:
    driver: bridge
volumes:
  sqlite_data: